name: console_log_handler

version: 0.1.4
author: Mike Mitterer  <office@mikemitterer.at>
description: Console logger

homepage: https://github.com/MikeMitterer/dart-console_log_handler

dependencies:
  browser: any

  logging: ">=0.9.2 <0.10.0"
  logging_handlers: ">=0.8.0 <0.9.0"

dev_dependencies:
  unittest: any