name: console_log_handler

version: 0.1.2
author: Mike Mitterer  <office@mikemitterer.at>
description: Console logger

homepage: https://github.com/MikeMitterer/dart-console_log_handler

dependencies:
  browser: any

  logging: any
  logging_handlers: any

dev_dependencies:
  unittest: any