name: console_log_handler

version: 0.5.0
author: Mike Mitterer  <office@mikemitterer.at>
description: Console logger

homepage: https://github.com/MikeMitterer/dart-console_log_handler

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  browser: ^0.10.0

  logging: ^0.11.0
  intl: any

  ansicolor: ^0.0.9
  supports_color: "^0.1.1"
         
dev_dependencies:
  test: any
  grinder: any