name: console_log_handler

version: 0.1.0
author: Mike Mitterer  <office@mikemitterer.at>
description: Console logger

dependencies:
  browser: any

  logging: any
  logging_handlers: any

dev_dependencies:
  unittest: any