name: console_log_handler_visual_test
version: 0.0.1
description: Visual Test for ConsolLogHandler
author: <Mike Mitterer> <office@mikemitterer.at>
#homepage: https://www.example.com

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:

  logging: ^0.11.0
  console_log_handler:
    path: ../..

dev_dependencies:

  build_runner: ^0.8.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
